### PR TITLE
Oracle Java 10

### PR DESCRIPTION
**Pull request by shawnhonsberger**
Download, PKG, and Munki Recipes for Oracle Java 10. I will create a
.jss in jss-recipes after merge.

### CODE REVIEW

**Comment by shawnhonsberger** [comment]
Hi @hjuutilainen how are you? I created this PR for Oracle Java 10. Thank you!

**Comment by hjuutilainen** [comment]
Thanks for the PR. The new recipes seem to be working fine and I'm fine with the changes. Since these are new recipes, I'm going to ask for a second review from @gregneagle or @timsutton.

**Comment by shawnhonsberger** [comment]
Thanks @hjuutilainen! :) And thank you @gregneagle and @timsutton!

**Comment by shawnhonsberger** [comment]
Thank you @hjuutilainen!

**Pull request merged**
