### PR TITLE
Post install script white space

### PR DESCRIPTION
**Pull request by mattydee99**
Removed leading white space from postinstall_script. PI will not get generated in pkgsinfo file otherwise.

### CODE REVIEW

**Comment by timsutton** [comment]
Sorry, I'm at a loss for what "PI" means?

**Comment by timsutton** [comment]
Even though we're doing a multi-line shell operation with `\` escapes I _think_ it should still be fine, but wondering if that's what you're referring to.

**Comment by mattydee99** [comment]
PI = post install script. 

It doesn't seem like white spaces should make a difference, but I could not find any evidence of the postinstall script being created in the package's pkgsinfo plist file. 

Making this change in an over ride fixed the issue for me.

**Comment by timsutton** [comment]
That's to be expected - AutoPkg uses the _entirety_ of your `pkginfo` key in your override, and doesn't do any deep merging between a parent recipe and your override. If the key exists in your override (which for `pkginfo` it normally would), then the version in your override is used.

While this sometimes can cause confusion for people, it also prevents you from having information added to your pkginfo which you weren't expecting. The addition of "recipe trust" in AutoPkg 1.0.0 now strongly guides admins to view changes to any recipes they have overridden, so at this point it's up to the admin to fix up this info in the override.

It's possible in the future we would add some kind of `AllowDeepMerging` option that an admin could selectively enable, if they felt confident with letting the parent recipe merge any keys that were missing in their override `pkginfo` key, for example.

Going back to the white space here, I just looked at my override and generated Spotify 1.0.52 pkginfo, and it doesn't appear the whitespace has caused any issue, so I'm going to close this so as to not make an unneeded modification to the recipe.

**Comment by mattydee99** [comment]
OK, I see what happened. Thanks for the clarification.

**Pull request closed without merging**
