### PR TITLE
Duplicate 2016 recipes and processor into new 2019 recipes and processor

### PR DESCRIPTION
**Pull request by carlashley**
This takes all the existing Office 2016 recipes and duplicates them for 2019 recipes.

Differences are:

2016 provider vs 2019 provider:
```
# git diff MSOffice2016URLandUpdateInfoProvider.py MSOffice2019URLandUpdateInfoProvider.py 
diff --git a/MSOfficeUpdates/MSOffice2019URLandUpdateInfoProvider.py b/MSOfficeUpdates/MSOffice2019URLandUpdateInfoProvider.py
old mode 100755
new mode 100644
index 7699f7f..ee5adec
--- a/MSOfficeUpdates/MSOffice2019URLandUpdateInfoProvider.py
+++ b/MSOfficeUpdates/MSOffice2019URLandUpdateInfoProvider.py
@@ -38,11 +38,11 @@ BASE_URL = "https://officecdn.microsoft.com/pr/%s/OfficeMac/%s.xml"
 # Note that Skype, 'MSFB' has a '16' after it, AutoUpdate has a '03' after it while all the other products have '15'
 
 PROD_DICT = {
-    'Excel': {'id': 'XCEL15', 'path': '/Applications/Microsoft Excel.app'},
-    'OneNote': {'id': 'ONMC15', 'path': '/Applications/Microsoft OneNote.app'},
-    'Outlook': {'id': 'OPIM15', 'path': '/Applications/Microsoft Outlook.app'},
-    'PowerPoint': {'id': 'PPT315', 'path': '/Applications/Microsoft PowerPoint.app'},
-    'Word': {'id': 'MSWD15', 'path': '/Applications/Microsoft Word.app'},
+    'Excel': {'id': 'XCEL2019', 'path': '/Applications/Microsoft Excel.app'},
+    'OneNote': {'id': 'ONMC2019', 'path': '/Applications/Microsoft OneNote.app'},
+    'Outlook': {'id': 'OPIM2019', 'path': '/Applications/Microsoft Outlook.app'},
+    'PowerPoint': {'id': 'PPT32019', 'path': '/Applications/Microsoft PowerPoint.app'},
+    'Word': {'id': 'MSWD2019', 'path': '/Applications/Microsoft Word.app'},
     'SkypeForBusiness': {'id': 'MSFB16', 'path': '/Applications/Skype for Business.app'},
     'AutoUpdate': {
         'id': 'MSau03',
```

For the recipes, basically all references to 2016 were updated with `sed 's/2016/2019/g'`. There really isn't any change for `OneDrive`, `SkypeForBusiness`, and `AutoUpdate` based on experiments, so the details in the 2019 processor are still the same, however those recipes may output a 2019 file name and 2019 details in `pkginfo`.

### CODE REVIEW

**Comment by carlashley** [comment]
Basically this is a copy+pasta+modify of the existing 2016 recipes and processors. I figured that there are scenarios where there may be a need to keep 2016 recipes around, but failing that, I'm happy if there's a desire not to merge for reasons about authorship, etc. The source details in the processor for production, insider, and fast insider don't appear to have changed based on the tests I've done, so if someone else wanted to build new processors and recipes, that's cool :)

**Comment by gregneagle** [comment]
I've not understanding the need for a new processor, then. Couldn't we just extend/adapt the existing processor?  Couldn't we just add new things to the PROD_DICT?
```
PROD_DICT = {
    'Excel': {'id': 'XCEL15', 'path': '/Applications/Microsoft Excel.app'},
    'OneNote': {'id': 'ONMC15', 'path': '/Applications/Microsoft OneNote.app'},
    'Outlook': {'id': 'OPIM15', 'path': '/Applications/Microsoft Outlook.app'},
    'PowerPoint': {'id': 'PPT315', 'path': '/Applications/Microsoft PowerPoint.app'},
    'Word': {'id': 'MSWD15', 'path': '/Applications/Microsoft Word.app'},
    'Excel2019': {'id': 'XCEL2019', 'path': '/Applications/Microsoft Excel.app'},
    'OneNote2019': {'id': 'ONMC2019', 'path': '/Applications/Microsoft OneNote.app'},
    'Outlook2019': {'id': 'OPIM2019', 'path': '/Applications/Microsoft Outlook.app'},
    'PowerPoint2019': {'id': 'PPT32019', 'path': '/Applications/Microsoft PowerPoint.app'},
    'Word2019': {'id': 'MSWD2019', 'path': '/Applications/Microsoft Word.app'},
    'SkypeForBusiness': {'id': 'MSFB16', 'path': '/Applications/Skype for Business.app'},
    'AutoUpdate': {
         'id': 'MSau03',
```

**Comment by carlashley** [comment]
That hadn't occurred to me. I guess that means then is just new recipes for 2019 would be required.

**Comment by carlashley** [comment]
@gregneagle - I've removed the 2019 processor and left the 2019 recipes in place.
The 2016 processor has had a few changes in order to make it work with the 2019 updates so packages are built with the right product year.

```
diff --git a/MSOffice2016URLandUpdateInfoProvider.py b/../../../autopkg_fork_20180928/recipes/MSOfficeUpdates/MSOffice2016URLandUpdateInfoProvider.py
index c0fc670..659afe5 100755
--- a/MSOffice2016URLandUpdateInfoProvider.py
+++ b/../../../autopkg_fork_20180928/recipes/MSOfficeUpdates/MSOffice2016URLandUpdateInfoProvider.py
@@ -15,7 +15,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 # Disabling 'no-env-member' for recipe processors
-#pylint:disable=e1101
+# pylint:disable=e1101
 """See docstring for MSOffice2016URLandUpdateInfoProvider class"""
 
 import plistlib
@@ -32,17 +32,25 @@ __all__ = ["MSOffice2016URLandUpdateInfoProvider"]
 CULTURE_CODE = "0409"
 BASE_URL = "https://officecdn.microsoft.com/pr/%s/OfficeMac/%s.xml"
 
-# These can be easily be found as "Application ID" in ~/Library/Preferences/com.microsoft.autoupdate2.plist on a 
+# These can be easily be found as "Application ID" in ~/Library/Preferences/com.microsoft.autoupdate2.plist on a
 # machine that has Microsoft AutoUpdate.app installed on it.
 #
 # Note that Skype, 'MSFB' has a '16' after it, AutoUpdate has a '03' after it while all the other products have '15'
+#
+# "Application ID" values changed for the Office 2019 apps. PROD_DICT updated with new values. Skype and
+# Microsoft Auto Update values have not changed.
 
 PROD_DICT = {
     'Excel': {'id': 'XCEL15', 'path': '/Applications/Microsoft Excel.app'},
+    'Excel2019': {'id': 'XCEL2019', 'path': '/Applications/Microsoft Excel.app'},
     'OneNote': {'id': 'ONMC15', 'path': '/Applications/Microsoft OneNote.app'},
+    'OneNote2019': {'id': 'ONMC2019', 'path': '/Applications/Microsoft OneNote.app'},
     'Outlook': {'id': 'OPIM15', 'path': '/Applications/Microsoft Outlook.app'},
+    'Outlook2019': {'id': 'OPIM2019', 'path': '/Applications/Microsoft Outlook.app'},
     'PowerPoint': {'id': 'PPT315', 'path': '/Applications/Microsoft PowerPoint.app'},
+    'PowerPoint2019': {'id': 'PPT32019', 'path': '/Applications/Microsoft PowerPoint.app'},
     'Word': {'id': 'MSWD15', 'path': '/Applications/Microsoft Word.app'},
+    'Word2019': {'id': 'MSWD2019', 'path': '/Applications/Microsoft Word.app'},
     'SkypeForBusiness': {'id': 'MSFB16', 'path': '/Applications/Skype for Business.app'},
     'AutoUpdate': {
         'id': 'MSau03',
@@ -59,6 +67,7 @@ CHANNELS = {
 }
 DEFAULT_CHANNEL = "Production"
 
+
 class MSOffice2016URLandUpdateInfoProvider(Processor):
     """Provides a download URL for the most recent version of MS Office 2016."""
     input_variables = {
@@ -99,9 +108,8 @@ class MSOffice2016URLandUpdateInfoProvider(Processor):
             "description":
                 ("Update feed channel that will be checked for updates. "
                  "Defaults to %s, acceptable values are either a custom "
-                 "UUID or one of: %s" % (
-                    DEFAULT_CHANNEL,
-                    ", ".join(CHANNELS.keys())))
+                 "UUID or one of: %s" % (DEFAULT_CHANNEL,
+                                         ", ".join(CHANNELS.keys())))
         }
     }
     output_variables = {
@@ -226,12 +234,16 @@ class MSOffice2016URLandUpdateInfoProvider(Processor):
             raise ProcessorError("Could not find an applicable update in "
                                  "update metadata.")
         item = item[0]
-        
+
         if self.env["version"] == "latest-standalone":
             p = re.compile(ur'(^[a-zA-Z0-9:/.-]*_[a-zA-Z]*_)(.*)Updater.pkg')
             url = item["Location"]
             (firstGroup, secondGroup) = re.search(p, url).group(1, 2)
-            item["Location"] = firstGroup + "2016_"+ secondGroup + "Installer.pkg"
+            if '2019' in PROD_DICT[self.env["product"]]['id']:
+                officeRelease = '2019_'
+            else:
+                officeRelease = '2016_'
+            item["Location"] = firstGroup + officeRelease + secondGroup + "Installer.pkg"
 
         self.env["url"] = item["Location"]
         self.output("Found URL %s" % self.env["url"])
@@ -257,7 +269,12 @@ class MSOffice2016URLandUpdateInfoProvider(Processor):
 
         # Minimum OS version key should exist always, but default to the current
         # minimum as of 16/11/03
-        pkginfo["minimum_os_version"] = item.get('Minimum OS', '10.10.5')
+        # 2018-09-27: Minimum OS for Office 2019 release is now 10.12.x
+        if '2019' in PROD_DICT[self.env["product"]]['id']:
+            minimumOS = '10.12'
+        else:
+            minimumOS = '10.10.5'
+        pkginfo["minimum_os_version"] = item.get('Minimum OS', minimumOS)
         installs_items = self.get_installs_items(item)
         if installs_items:
             pkginfo["installs"] = installs_items
```

**Pull request closed without merging**
