### PR TITLE
Update for mozilla URL path changes

### PR DESCRIPTION
**Pull request by ih84ds**
Index path requlres trailing '/' to avoid 404.
Handle multiple versions being listed (use the last one).
Handle absolute file href.

### CODE REVIEW

**Comment by timsutton** [comment]
Thanks - there's an assumption, though, that these will be always listed in ascending alphabetical order, and that the last item will always be the highest actual version. What would be ideal is to use something like `distutils.version`'s `LooseVersion` to sort by actual versions, and test that the file pattern matches something like "Product version.dmg." Some other processors in this repo and autopkglib (like the Sparkle update provider) do this already.

Is that something you'd be willing to add to this?

**Comment by ih84ds** [comment]
Sure, I can take a look. Makes sense to not make assumptions about the sort order when possible.

**Comment by ih84ds** [comment]
The above change seems to accomplish the task.

**Comment by timsutton** [comment]
I'm not sure whether comparing the entire path as a "version" is any more useful than relying on the FTP directory listing sort order. For example, for latest-beta, LooseVersion is trying to make sense of a version called `/pub/firefox/releases/latest-beta/mac/en-US/Firefox%2042.0b6.dmg`.

One way to do this would be to put each match into a dict associated with a version key extracted from the basename. It should then be possible to sort by your comparison function according to the key.

**Comment by ih84ds** [comment]
The way I understand that LooseVersion works is that is separates the string into chunks of numerics and non-numerics. So each of the paths would start with an identical chunk of "/pub/firefox/releases/latest-beta/mac/en-US/Firefox%20", which would become irrelevant. Adding a parser would essentially just strip off the (identical) prefixes and suffixes in the path. I could be wrong, but that was my interpretation.

**Comment by timsutton** [comment]
You can verify for yourself exactly what LooseVersion does, but I did a simple test:

```python
from distutils.version import LooseVersion as LV

a = LV('/pub/firefox/releases/latest-beta/mac/en-US/Firefox%2042.0.dmg')
b = LV('/pub/firefox/releases/latest-beta/mac/en-US/Firefox%2042.0.1.dmg')
a < b

False
```

It does the "right" thing if I compare `42.0.1` and `42.0.2` as in the current releases, but not with a `42.0`.

**Comment by ih84ds** [comment]
Ah, you're right. The url encoding could also potentially throw it off I would guess. Added a basic version parser in the latest revision. Thanks for the assistance!

**Comment by timsutton** [comment]
Looks good! I also tested against the case where there's a version like `42.0` and your version parser works as expected.

**Pull request merged**
