### PR TITLE
Adobe reader multilanguage

### PR DESCRIPTION
**Pull request by choules**
Hi all,

please have look at: https://groups.google.com/d/msg/autopkg-discuss/ZisR54Fm6wo/KdkVDY3ekjQJ

I have stumbled across the same problem with our German customers. Adobe releases no full installer for non-english versions of Adobe Reader, but just an updater. I have modified the url provider to support the updater pkgs and added to processors to support the international updates. (These are my first steps with Python, so please excuse any extraordinary code snippets ;-))

I have tested the workflow at our site and it has worked fine.

Best,
Matthias

### CODE REVIEW

**Comment by choules** [comment]
Hi Tim,

you are absolutely right: The language key is not relevant for the updater, just for the base installation. I have removed it from the updater recipe. And I have added an input variable for the base name to set the update_for key respectively. The requires key has been removed. I still need to test this, hopefully tomorrow.

**Comment by timsutton** [comment]
Took another look at this since the latest update didn't include a full installer at all.

My initial tests of doing a `make-override` on your AdobeReaderUpdates.munki recipe, verifying my `BASENAME` variable seemed to produce an OK install. I did a test of upgrading both my existing 11.0.10 install on my desktop, and doing a full install + update run at the loginwindow in a VM.

The installs item you merge in with the Munki recipe matches the output of `makepkginfo -f` minus the (irrelevant IMO) minimum OS version of 10.4.3.

Since the AdobeReaderUpdates recipes would only ever be meant to be used with the MUL updaters, and since the AdobeReaderURLProvider processor has since been updated to include some support for the new DC versions (and is thus harder to merge in).. I'd actually be more in favor of simplifying the logic by putting your additions to this processor into its own processor that's exclusively for Reader MUL updaters.

Maybe it would eventually even be possible that a separate MUL updater processor could support DC as well, if DC follows the same pattern having most languages only supported via MUL updaters.

It's unfortunate that Adobe doesn't adhere to a predictable pattern of these installers, so most people who'd otherwise be able to use full installers will be forever confused about whether or not they need the updates recipes, or when one supercedes the other, etc.

**Comment by choules** [comment]
That sounds good. I will take a look at making the separate processor and will then have a look at the DC options. Thanks for your feedback!

**Comment by timsutton** [comment]
I didn't go so far as looking at DC yet - have no immediate plans to - but I incorporated your new recipe and processor, and added some additional logic (sending client OS X versions in the template URL string) that I found needed to be added in the latest updates that came out a few weeks ago. I also 

Added in this commit: https://github.com/autopkg/recipes/commit/f4bd153a7d1bc819fd29cc34b40ef3311656a29c

**Pull request closed without merging**
