### PR TITLE
Add version number to name of AdobeReader XI Installer.pkg

### PR DESCRIPTION
**Pull request by mhershberger**
Added code to get the version number from the Distribution file and append it to the final pkg name.

### CODE REVIEW

**Comment by homebysix** [comment]
See also: https://github.com/autopkg/jss-recipes/pull/51

**Comment by timsutton** [comment]
Thanks!

You'll need to also add `version` to the processor's output variables, however, in order for AutoPkg to copy out this variable into `env` for use by downstream processors.

**Comment by mhershberger** [comment]
I just updated it with those two changes (adding version to output variables and changing the delimiter to "-").

**Comment by timsutton** [comment]
Thanks! Would you be able to squash these to one commit with a short descriptive commit message?

**Comment by mhershberger** [comment]
Sure. I'm new to GitHub, so excuse me if I'm going about this wrong. I created a new branch in my fork, called AdobeReaderVersion, with only one commit. I don't see a way to edit this pull request to use that branch, or edit the original branch to remove or merge those commits. What's the normal approach here? Sorry for the newbie question.

**Comment by timsutton** [comment]
No problem - GitHub doesn't AFAIK provide a way to change the branch once a PR has been opened. Since you've made the fixup in a new branch, we'll just close this PR and you can open a new one against your AdobeReaderVersion branch.

**Pull request closed without merging**
