### PR TITLE
Switched to strict sh comparison syntax.

### PR DESCRIPTION
**Pull request by homebysix**

### CODE REVIEW

**Comment by gregneagle** [comment]
[[ ]] seems to be working fine; if that's not strictly correct why not switch to [ ] instead? (I tend to favor using plain old vanilla /bin/sh over bash if at all possible. I'm not sure why; it just seems simpler and less "flavor-of-the-month". You see, I remember when people were using tcsh and csh and zsh, etc. Things seem to have settled (somewhat) on bash these days, but who knows what the next hotness will be. So I prefer (for simple shell scripts) plain old boring /bin/sh. Feel free to convince me otherwise.)

**Comment by timsutton** [comment]
As far as I can tell, /bin/sh _is_ Bash on OS X:

```
$ /bin/sh --version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```

/bin/bash and /bin/sh differ by a few bytes and aren't identical, but they report the same version.

I don't think OS X is unique in this regard, either. When Shellshock was new I think a lot of Linux admins discovered the same thing.

**Comment by gregneagle** [comment]
It's actually more subtle than that: bash actually changes its behavior when it is called as "sh".

And again, that's the _current_ configuration. Pretty sure sh != bash on, say OS X 10.0...

**Comment by homebysix** [comment]
Updated PR to use sh, with the strict `[ "$3" = "/" ]` syntax recommended by the shellcheck linter.

**Comment by seansgm** [comment]
As Greg said, sh != bash on OSX.
Eg. Process substitution, bash only.

**Pull request merged**
