### PR TITLE
Update MSOfficeMacURLandUpdateInfoProvider.py

### PR DESCRIPTION
**Pull request by kevinmcox**
Changes the path for MS Teams to include "classic."

### CODE REVIEW

**Comment by gregneagle** [comment]
Might there are be a new dict to be added for the _other_ Teams app?

**Comment by kevinmcox** [comment]
@gregneagle could be, but I didn't dig into if there was a way to get these recipes to pull down that other Teams app. By default the Teams.munki recipe pulls the _classic_ app.

**Comment by gregneagle** [comment]
Sure. I was just curious if maybe there was a new id for the new Teams; something like:
```
"id": "TEAMS20"
```

**Comment by gregneagle** [comment]
(We don't really use any version of Teams here, so it's more work than I'm willing to put in to find this out myself)

**Pull request merged**
