### PR TITLE
Workaround for SSL issues with BareBonesURLProvider.py

### PR DESCRIPTION
**Pull request by hansen-m**

### CODE REVIEW

**Comment by hansen-m** [comment]
Monkey-patch, but it provides a workaround to the Python SSL issues with <= 10.10.4.

**Comment by timsutton** [comment]
Thanks - I'm ok with the hack workaround, which seems to work on older OSes. Can you fix up the PyLint errors?

**Comment by hansen-m** [comment]
Done!

**Comment by gregneagle** [comment]
What happens with Python 2.7.10 in OS X 10.10.5 and 10.11? Does urlib2/ssl support TLS higher than 1?

Just wondering if this needs to be conditional based on Python or SSL version, so that when other modules are updated, this patch doesn't do the wrong thing.

**Comment by hansen-m** [comment]
Agreed, this should be conditional. I've only tested this on 10.10.4.

Only needed for OS < 10.10.5, Python < 2.7.10 or OpenSSL < 0.9.8za 5 Jun 2014 -- correct?

**Comment by gregneagle** [comment]
I actually don't know. I think the Python and OpenSSL relationships are a bit more complex.

**Comment by gregneagle** [comment]
Let's merge this now, but it may well need to be revisited in the future as we better understand all the (complex) issues at hand. I'd be more concerned about getting this "right" if this was a general-purpose processor.

**Pull request merged**
