### PR TITLE
Update Dropbox.munki.recipe

### PR DESCRIPTION
**Pull request by mattydee99**
set helper script to 4511 not 04511 for suid.

### CODE REVIEW

**Comment by timsutton** [comment]
Can you elaborate on your reason for this change?

**Comment by mattydee99** [comment]
I assumed that 04511 was a typo. Wouldn't 4511 be the way to set suid on
the script? r-s--x--x
I noticed this after the post install script did not set the bit properly
on one of my machines (Sierra; I was able to reproduce error). It looks
like 04511 works sometimes, perhaps depending on the Mac OS version, and
which extended perms are present on the file when the command is run. That
looks wrong to me though; I believe the proper syntax is 4511.

**Comment by gregneagle** [comment]
Python can be confusing in this regard. 04511 is octal; 4511 is decimal...

**Comment by gregneagle** [comment]
```python
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print 04511
2377
>>> print 4511
4511
```

**Comment by gregneagle** [comment]
..and I now see it's an embedded shell script, so forget my comments about Python.

**Comment by timsutton** [comment]
The `04511` _shouldn't_ make a difference in BSD's `chmod` - that line has been unchanged since it was added in 2013.

There _was_ a related change added to accommodate Sierra, but it had to do with the order of `chown` and `chmod`, where if they didn't happen in a specific order on Sierra that the setuid bit would be lost. Perhaps that's the error you encountered?

**Comment by mattydee99** [comment]
Ah. Thanks for the clarification. That's likely the issue. Is there a
reason to keep the leading 0 there though? It doesn't seem like there
should be 5 digits there. http://man.openbsd.org/chmod.1
Although it looks like chmod will accept 174511 (ignoring the first 2
digits), but no more :)

**Comment by timsutton** [comment]
Going to close this as it seems like the leading 0 issue is a stylistic choice and the recipe seems to still be working fine.

**Pull request closed without merging**
